<?php

/*
	Do not edit this file manually. This copy of global file is overwritten
	by extensions editor.
*/

$installed_extensions = array (
  4 => 
  array (
    'package' => 'salescontainer',
    'name' => 'salescontainer',
    'version' => 'zz-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/salescontainer',
    'active' => 1,
  ),
  7 => 
  array (
    'package' => 'export_invoice',
    'name' => 'export_invoice',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/export_invoice',
    'active' => 1,
  ),
);
?>