<?php

/*
	Do not edit this file manually. This copy of global file is overwritten
	by extensions editor.
*/

$installed_extensions = array (
  4 => 
  array (
    'package' => 'salescontainer',
    'name' => 'salescontainer',
    'version' => 'zz-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/salescontainer',
    'active' => 1,
  ),
  7 => 
  array (
    'package' => 'export_invoice',
    'name' => 'export_invoice',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/export_invoice',
    'active' => 1,
  ),
  8 => 
  array (
    'package' => 'systype_attachment',
    'name' => 'systype_attachment',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/systype_attachment',
    'active' => 1,
  ),
  9 => 
  array (
    'name' => 'Theme Elegant',
    'package' => 'elegant',
    'version' => '2.3.0-7',
    'type' => 'theme',
    'active' => false,
    'path' => 'themes/elegant',
  ),
  10 => 
  array (
    'name' => 'Theme Fancy',
    'package' => 'fancy',
    'version' => '2.3.0-5',
    'type' => 'theme',
    'active' => false,
    'path' => 'themes/fancy',
  ),
  11 => 
  array (
    'name' => 'Theme Modern',
    'package' => 'modern',
    'version' => '2.3.0-5',
    'type' => 'theme',
    'active' => false,
    'path' => 'themes/modern',
  ),
  12 => 
  array (
    'package' => 'cheque_reminder',
    'name' => 'cheque_reminder',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/cheque_reminder',
    'active' => 1,
  ),
  14 => 
  array (
    'package' => 'other_report',
    'name' => 'other_report',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/other_report',
    'active' => 1,
  ),
);
?>